name: Publish and Release AGS Package

on:
  push:
    branches:
      - main
    paths:
      - 'ags/**'  
      - '.github/workflows/publish-and-release-ags-lib.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --workspage ags
      - run: npm publish --workspace ags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
