name: Publish and Release AGS Package

on:
  push:
    branches:
      - main

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Get version of the ags package
        id: get_version
        run: |
          VERSION=$(jq -r '.version' ags/package.json)
          echo "ags_version=$VERSION" >> $GITHUB_ENV

      - name: Publish ags package to npm
        run: npm publish --workspace ags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: contains(github.event.head_commit.message, 'chore(release)')

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v2
        with:
          tag_name: "ags-v${{ env.ags_version }}"
          release_name: "AGS Library v${{ env.ags_version }}"
          body: |
            Release of version ${{ env.ags_version }} of the AGS library.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
